### PR TITLE
Updated cssKeyframeRegex to fix bug that removed chunks of CSS preceding "keyframes"

### PR DESCRIPTION
**Pull request by mortenson**
This PR updates the cssKeyframeRegex to fix a bug where occurrences of "keywords" would cause a significant chunk of CSS to be improperly removed. You can see this in the example below:

```
$ css = new cssjs();
$ css.parseCSS('@font-family{source:url("")}keyframes foo{ foo{top: 0px;} }')
$ foo[0].selector
 "@keyframes"
$ foo[0].styles
 "@font-family{source:url("")}keyframes foo{ foo{top: 0px;} }"
$ foo[0].type
 "keyframes"
```

### CODE REVIEW

**Comment by kemaldaggen** [comment]
Thanks for the Pull request. It seems not to be breaking the unit tests.  I'll investigate the issue and accept it in couple of days!

**Comment by mortenson** [comment]
Have you gotten a chance to look at this @cettox? Thanks!

**Comment by mortenson** [comment]
Any update @cettox? This will need to be manually merged at this point but is a pretty minor change.

**Comment by kemaldaggen** [comment]
Sorry for waiting you so long, thanks for the contribution!

**Pull request merged**
